export const puppyList = [
  {
    id: 1,
    name: "Sir Waggington",
    email: "sir-wag@email.com",
    isCute: true,
    age: 5,
    ownerId: 1,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFUAfyVe3Easiycyh3isP9wDQTYuSmGPsPQvLIJdEYvQ_DsFq5Ez2Nh_QjiS3oZ3B8ZPfK9cZQyIStmQMV1lDPLw",
    tricks: [
      { id: 2, title: "Lay Down" },
      { id: 3, title: "Jump through flaming hoop" },
    ],
  },
  {
    id: 2,
    name: "Fiona Penny Pickles",
    email: "pick-your-pennies@email.com",
    isCute: true,
    age: 6,
    ownerId: 1,
    image: "https://i.natgeofe.com/n/4f5aaece-3300-41a4-b2a8-ed2708a0a27c/domestic-dog_thumb_3x2.jpg",
    tricks: [],
  },
  {
    id: 3,
    name: "Professor Wagglesworth",
    email: "waggie@email.com",
    isCute: true,
    age: 6,
    ownerId: 2,
    image:
      " https://images.aeonmedia.co/images/acd6897d-9849-4188-92c6-79dabcbcd518/essay-final-gettyimages-685469924.jpg?width=3840&quality=75&format=auto",
    tricks: [{ id: 1, title: "Sit" }],
  },
  {
    id: 4,
    name: "Sergeant Barkowitz",
    email: "the-sarge@email.com",
    isCute: true,
    age: 4,
    ownerId: 2,
    image: "https://www.cdc.gov/healthy-pets/media/images/2024/04/GettyImages-598175960-cute-dog-headshot.jpg",
    tricks: [{ id: 2, title: "Lay Down" }],
  },
  {
    id: 5,
    name: "Captain Sniffer",
    email: "capn-sniff@email.com",
    isCute: true,
    age: 7,
    ownerId: 3,
    image:
      "https://images.squarespace-cdn.com/content/v1/54822a56e4b0b30bd821480c/45ed8ecf-0bb2-4e34-8fcf-624db47c43c8/Golden+Retrievers+dans+pet+care.jpeg?format=750w ",
    tricks: [],
  },
  {
    id: 6,
    name: "Miss Furbulous",
    email: "miss-furby@email.com",
    isCute: true,
    age: 1,
    ownerId: 3,
    image: "https://cdn-prod.medicalnewstoday.com/content/images/articles/322/322868/golden-retriever-puppy.jpg ",
    tricks: [],
  },
  {
    id: 7,
    name: "Alfred von Wigglebottom",
    email: "alfie@email.com",
    isCute: true,
    age: 2,
    ownerId: 3,
    image:
      "https://www.earth.com/assets/_next/image/?url=https%3A%2F%2Fcff2.earth.com%2Fuploads%2F2023%2F04%2F12130717%2FSmall-dogs-1400x850.jpg&w=1200&q=75 ",
    tricks: [],
  },
];
